# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.
local_resource(
    'deploy',
    'python record-start-time.py',
)

local_resource(
    'compile',
    'mvn clean package',
    deps=['src', 'pom.xml'],
    resource_deps = ['deploy']
)

docker_build('orders-service', '.', dockerfile='./Dockerfile')
k8s_yaml('deploy.yaml')
k8s_resource('orders-service', port_forwards=8080, resource_deps=['deploy','compile'])