apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: config-via-springcloud-k8s-demo-service
  name: config-via-springcloud-k8s-demo-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: config-via-springcloud-k8s-demo-service
  name: config-via-springcloud-k8s-demo-service:view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: config-via-springcloud-k8s-demo-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]