kind: Service
apiVersion: v1
metadata:
  name: discovery-client-demo
spec:
  selector:
    app: discovery-client-demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-client-demo
spec:
  selector:
    matchLabels:
      app: discovery-client-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-client-demo
    spec:
      # reuse service account for configMap demo, so discovery client can access services
      serviceAccount: config-via-springcloud-k8s-demo-service
      containers:
        - name: discovery-client-demo
          image: discovery-client-demo
          imagePullPolicy: Never
          ports:
            - containerPort: 8080