kind: Service
apiVersion: v1
metadata:
  name: tracing-by-sleuth-and-zipkin
spec:
  selector:
    app: tracing-by-sleuth-and-zipkin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-by-sleuth-and-zipkin
spec:
  selector:
    matchLabels:
      app: tracing-by-sleuth-and-zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: tracing-by-sleuth-and-zipkin
    spec:
      containers:
        - name: tracing-by-sleuth-and-zipkin
          image: tracing-by-sleuth-and-zipkin
          imagePullPolicy: Never
          ports:
            - containerPort: 8080