apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: tracing-by-sleuth-and-zipkin
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - deploy.yaml