apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: distributed-tracing-demo-service
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - deploy.yaml