apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: config-demo-service
  name: config-demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-demo-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-demo-service
    spec:
      containers:
      - image: haodeng/config-demo-service:latest
        name: config-demo-service
        resources: {}
        env:
          - name: DEMO_VALUE1
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: demo_value1
          - name: DEMO_VALUE2
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: demo_value2
status: {}
