apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot-k8s-demo
  name: springboot-k8s-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-k8s-demo
  type: ClusterIP
status:
  loadBalancer: {}
